# ── Database ──────────────────────────────────────
# Note: "mysql" is the Docker container name
# Docker Compose creates DNS for each service name
spring.datasource.url=jdbc:mysql://mysql:3306/eventdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=     ${DB_USERNAME}
spring.datasource.password=     ${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA ───────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ── Redis ─────────────────────────────────────────
# "redis" is the container name
spring.data.redis.host=redis
spring.data.redis.port=6379

# ── Elasticsearch ─────────────────────────────────
# "elasticsearch" is the container name
spring.elasticsearch.uris=http://elasticsearch:9200

# ── Email ─────────────────────────────────────────
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ── JWT ───────────────────────────────────────────
app.jwt.secret=${JWT}
app.jwt.expiration=86400000

# ── Geocoding ─────────────────────────────────────
app.geocoding.api-key=${OPENAI_KEY}

# ── Spring AI ─────────────────────────────────────
spring.ai.openai.api-key=${OPENAI_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama3-8b-8192

# ── Server ────────────────────────────────────────
server.port=8081