# Active profile — change to prod on production server
spring.profiles.active  =dev

# Common settings shared across all profiles
spring.application.name = event-management

# JPA
spring.jpa.show-sql     =   false
spring.jpa.open-in-view =   false

# Flyway
spring.flyway.enabled   =true
spring.flyway.locations =classpath:db/migration

# Swagger
springdoc.api-docs.path                 =/api-docs
springdoc.swagger-ui.path               =/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled =true