ALTER TABLE events
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'PUBLISHED',
ADD COLUMN published_at DATETIME,
ADD COLUMN cancelled_at DATETIME,
ADD COLUMN completed_at DATETIME,
ADD COLUMN cancellation_reason VARCHAR(500);